BOARD_TAG   	= mega
BOARD_SUB	  	= atmega2560 
USER_LIB_PATH 	= $(realpath ../lib)
ARDUINO_DIR   	= /opt/arduino-1.8.3
ARDUINO_LIBS  	= Wire SPI OneWire \
				  Adafruit_BME280 Adafruit_Sensor \
				  istsos LiquidCrystal  BH1750 \
				  DallasTemperature DHT LowPower RTClib

include ../Arduino.mk
