BOARD_TAG   	= mega
BOARD_SUB	  	= atmega2560
USER_LIB_PATH 	= $(realpath ../../../../libraries)
ARDUINO_DIR   	= /opt/arduino-1.8.4
ARDUINO_LIBS  	= istsos

# SERVER 			= '"geoservice.ist.supsi.ch"'
# URI 			= '"/4onse/wa/istsos/services/sos/operations/fastinsert"'
# PROCEDURE_ID 	= '"ebd76b2c985a11e79e2008002745029a"'
#
# APN				= '"gprs.swisscom.ch"'
# APNUSER			= '"gprs"'
# PASS			= '"gprs"'


include ../../../../Arduino.mk
